---
title: "Setup ENV"
author: "Ha Truong"
date: "2023-10-06"
date-modified: "2023-10-06"
categories: [code]
---

# Setup ENV
A guidline for myself to setup env for ML

**Note: NEVER use python of system => use CONDA or MAMBA to manage python version**

## Mamba: manage python package
- Currently, Mamba is faster than Miniconda, I follow the instruction here to install: https://github.com/conda-forge/miniforge#mambaforge
  ```
  
  # MACOS 
  (base) 192 :: ~ » curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" bash Miniforge3-$(uname)-$(uname -m).sh
  (base) 192 :: ~ » which python3                                                                                                                                                                         1 ↵
  /Users/hatruong/miniforge3/bin/python3
  (base) 192 :: ~ » python3 --version
  Python 3.10.12

  (base) 192 :: ~ » alias python=python3
  (base) 192 :: ~ » which python
  python: aliased to python3
  
  ```
  Note: I use python3.10 because this is version that Google Colab using

- Virtual Env:
  ```
  mamba create -n <nameofmyenv>
  mamba activate <nameofmyenv>
  ```

- Install packages from files:
  ```
  mamba install --file <path_of_requirements>
  ```

## Fastai

- install fastai using mamba
  ```
  mamba install -Uqq fastai
  ```

## Quarto: blogging

- install: https://quarto.org/docs/get-started/
- failed to preview + render with vscode so I try with terminal and it works!
- it automatically update when I change file
- how to publish blog to github: https://quarto.org/docs/publishing/github-pages.html
  ```
  # create a branch for publishing
  git checkout --orphan gh-pages
  git reset --hard # make sure you've committed changes before running this!
  git commit --allow-empty -m "Initialising gh-pages branch"
  git push origin gh-pages

  # update gitignore
  /.quarto/
  /_site/

  # publishing
  quarto publish gh-pages
  ```

## Jupyter notebook

- it is automatically installed by mamba but there is an incompatible between jupyter notebook and extension (at day of 2023.10.06, version of notebook is 7.x.x which is not work with extension => we need to downgrade)
  ```
  pip install --upgrade notebook==6.4.12
  // reinstall traitlets
  pip uninstall traitlets
  pip install traitlets==5.9.0
  ```
- install **jupyter_contrib_nbextensions**
  ```
  pip install jupyter_contrib_nbextensions
  jupyter contrib nbextension install --user
  
  ```
  Some useful extensions: Codefolding, Collapse Heading, Table of Content
- auto-format code: step (1) ```pip install autopep8```, step (2) enable autopep8 in nbextensions
- to view document of func in jupyter notebook, we install ```pip install nbdev```
- Convert notebook to python script, we use `nbdev.export.nb_export` Please refer to this file for example: `https://huggingface.co/spaces/hatruong/minima/blob/main/app.ipynb`


## Setup Deeplearning
- CUDA:
  ```
  # check if cuda is really installed or not
  nvcc --version
  #
  # install
  sudo apt install nvidia-cuda-toolkit
  ```
- Some common packages
  ```
  diffusers
  transformers
  huggingface-hub
  ```